import { Express } from 'express';
import { Role } from '../user/user_role.enum';
import { AsbWithRelationsDto } from 'src/application/asb/dto/asb_with_relations.dto';
import { FindAllAsbDto } from 'src/application/asb/dto/find_all_asb.dto';
import { AsbListResultDto } from 'src/application/asb/dto/asb_list_result.dto';
import { CreateAsbStoreIndexDto } from 'src/application/asb/dto/create_asb_store_index.dto';
import { UpdateAsbStoreIndexDto } from 'src/application/asb/dto/update_asb_store_index.dto';
import { UpdateAsbStoreLantaiDto } from 'src/application/asb/dto/update_asb_store_lantai.dto';
import { StoreBpsDto } from 'src/presentation/asb/dto/store_bps.dto';
import { StoreBpnsDto } from 'src/presentation/asb/dto/store_bpns.dto';
import { StoreRekeningDto } from 'src/presentation/asb/dto/store_rekening.dto';
import { StoreVerifDto } from 'src/presentation/asb/dto/store_verif.dto';
import { VerifyLantaiDto } from 'src/presentation/asb/dto/verify_lantai.dto';
import { VerifyBpnsDto } from 'src/presentation/asb/dto/verify_bpns.dto';
import { VerifyRekeningDto } from 'src/presentation/asb/dto/verify_rekening.dto';
import { VerifyPekerjaanDto } from 'src/presentation/asb/dto/verify_pekerjaan.dto';
import { GetAsbByMonthYearDto } from 'src/application/asb/dto/get_asb_by_moth_year.dto';
import { VerifyBpsDto } from 'src/presentation/asb/dto/verify_bps.dto';

export abstract class AsbService {
    abstract findById(id: number, userIdOpd: number | null, userRoles: Role[]): Promise<AsbWithRelationsDto | null>;
    abstract findAll(dto: FindAllAsbDto, userIdOpd: number | null, userRoles: Role[]): Promise<AsbListResultDto>;
    abstract getAsbByMonthYear(dto: GetAsbByMonthYearDto, userIdOpd: number | null, userRoles: Role[]): Promise<{ date: string; count: number }[]>;
    abstract getAsbByMonthYearStatus(dto: GetAsbByMonthYearDto, userIdOpd: number | null, userRoles: Role[]): Promise<{ asbStatus: string; amount: number }[]>;
    abstract createIndex(dto: CreateAsbStoreIndexDto, userIdOpd: number | null, userRoles: Role[], username: string): Promise<{ id: number; status: any }>;
    abstract updateIndex(dto: UpdateAsbStoreIndexDto, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract deleteAsb(id: number, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number }>;
    abstract storeLantai(dto: UpdateAsbStoreLantaiDto, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract storeBps(dto: StoreBpsDto, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract storeBpns(dto: StoreBpnsDto, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract storeRekening(dto: StoreRekeningDto, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract storeVerif(dto: StoreVerifDto, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract verifyLantai(dto: VerifyLantaiDto, userId: string | null, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract verifyBps(dto: VerifyBpsDto, userId: string | null, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract verifyBpns(dto: VerifyBpnsDto, userId: string | null, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract verifyRekening(dto: VerifyRekeningDto, userId: string | null, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract verifyPekerjaan(dto: VerifyPekerjaanDto, userId: string | null, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract verify(id_asb: number, userId: string | null, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
    abstract reject(id_asb: number, rejectReason: string, userIdOpd: number | null, userRoles: Role[]): Promise<{ id: number; status: any }>;
}
