export enum DocumentSpec {
    SURAT_REKOMENDASI = 'SURAT_REKOMENDASI',
    SURAT_PERMOHONAN = 'SURAT_PERMOHONAN',
    KERTAS_KERJA = 'KERTAS_KERJA',
    LAPORAN = 'LAPORAN',
    MATERI = 'MATERI',
}
