services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: easb-backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - easb-net

networks:
  easb-net:
    external: true
