import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedSatuans1763651220000 implements MigrationInterface {
    name = 'SeedSatuans1763651220000';

    public async up(queryRunner: QueryRunner): Promise<void> {
        const satuans = [
            { satuan: 'Liter' },
            { satuan: 'Luas / M2' },
            { satuan: 'Lusin' },
            { satuan: 'M' },
            { satuan: 'M / Lari' },
            { satuan: 'M1' },
            { satuan: 'M2' },
            { satuan: 'M2 Kedalaman S.D 1 M' },
            { satuan: 'M2 Per Bulan' },
            { satuan: 'M2 Per Hari' },
            { satuan: 'M2/Tahun' },
            { satuan: 'M3' },
            { satuan: 'M3"' },
            { satuan: 'Macam' },
            { satuan: 'Materi' },
            { satuan: 'Media' },
            { satuan: 'Menit' },
            { satuan: 'Meter' },
            { satuan: 'Minggu' },
            { satuan: 'Ml' },
            { satuan: 'MMKolom' },
            { satuan: 'Ons' },
            { satuan: 'Orang' },
            { satuan: 'Orang / Acara' },
            { satuan: 'Orang / Alamat' },
            { satuan: 'Orang / Bulan' },
            { satuan: 'Orang / Bulan / Kegiatan' },
            { satuan: 'Orang / Hari' },
            { satuan: 'Orang / Jam' },
            { satuan: 'Orang / Jam / Pelajaran' },
            { satuan: 'Orang / Kali' },
            { satuan: 'Orang / Kamar' },
            { satuan: 'Orang / Kedatangan' },
            { satuan: 'Orang / Keg. / Bln' },
            { satuan: 'Orang / Kegiatan' },
            { satuan: 'Orang / Materi' },
            { satuan: 'Orang / Paket / Pekerjaan' },
            { satuan: 'Orang / Perjalanan' },
            { satuan: 'Orang / PP' },
            { satuan: 'Orang / Sessi' },
            { satuan: 'Orang / Session' },
            { satuan: 'Orang / Titik' },
            { satuan: 'Organisasi' },
            { satuan: 'Pack' },
            { satuan: 'Pail' },
            { satuan: 'Pak' },
            { satuan: 'Parpol' },
            { satuan: 'Pasang' },
            { satuan: 'Pc' },
            { satuan: 'Pcs' },
            { satuan: 'Pekerjaan' },
            { satuan: 'Pelepah' },
            { satuan: 'Pendampingan' },
            { satuan: 'Per 100 Lembar' },
            { satuan: 'Per Balok' },
            { satuan: 'Per Batang' },
            { satuan: 'Per Batang Pohon' },
            { satuan: 'Per Buku' },
            { satuan: 'Per Bulan' },
            { satuan: 'Per Bungkus' },
            { satuan: 'Per Detik' },
            { satuan: 'Per Keping' },
            { satuan: 'Per Kotak' },
            { satuan: 'Per Liputan' },
            { satuan: 'Per Orang' },
            { satuan: 'Per Rim' },
            { satuan: 'Per Ruang' },
            { satuan: 'Per Sampel' },
            { satuan: 'Per Tayang' },
            { satuan: 'Per Titik' },
            { satuan: 'Persen' },
            { satuan: 'Pert 100 Buah' },
            { satuan: 'Pick Up' },
            { satuan: 'Porsi' },
            { satuan: 'Posyandu' },
            { satuan: 'Pot' },
            { satuan: 'Produk Hukum' },
            { satuan: 'Pulsa' },
            { satuan: 'Rean' },
            { satuan: 'Regu' },
            { satuan: 'Rim' },
            { satuan: 'Roll' },
            { satuan: 'Roll Besar' },
            { satuan: 'Rupiah' },
            { satuan: 'RW' },
            { satuan: 'Sachet' },
            { satuan: 'Sampel' },
            { satuan: 'Sekolah' },
            { satuan: 'Semester' },
            { satuan: 'Sesi' },
            { satuan: 'Set' },
            { satuan: 'Shift' },
            { satuan: 'Siklus' },
            { satuan: 'Siswa' },
            { satuan: 'Stel' },
            { satuan: 'Strip' },
            { satuan: 'Supp' },
            { satuan: 'Surat' },
            { satuan: 'Tablet' },
            { satuan: 'Tabung' },
            { satuan: 'Tahun' },
            { satuan: 'Tangki (4000 Liter)' },
            { satuan: 'Tayang / Spot' },
            { satuan: 'Tayang / Spot Durasi 30 Detik' },
            { satuan: 'Tempat' },
            { satuan: 'Titik' },
            { satuan: 'Titik Lampu' },
            { satuan: 'Ton' },
            { satuan: 'Triwulan' },
            { satuan: 'Tube' },
            { satuan: 'Unit' },
            { satuan: 'Unit / Bulan' },
            { satuan: 'Unit / Pompa' },
            { satuan: 'Unit / Tahun' },
            { satuan: 'USK' },
            { satuan: 'VA' },
            { satuan: 'Vial' },
            { satuan: 'Watt' },
            { satuan: 'Zak' },
        ];

        for (const satuan of satuans) {
            await queryRunner.query(
                `INSERT INTO "satuans" ("satuan", "is_active")
                 VALUES ($1, $2)
                 ON CONFLICT ("satuan") DO NOTHING`,
                [satuan.satuan, true],
            );
        }
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const satuanList = [
            'Liter','Luas / M2','Lusin','M','M / Lari','M1','M2','M2 Kedalaman S.D 1 M',
            'M2 Per Bulan','M2 Per Hari','M2/Tahun','M3','M3"','Macam','Materi','Media',
            'Menit','Meter','Minggu','Ml','MMKolom','Ons','Orang','Orang / Acara',
            'Orang / Alamat','Orang / Bulan','Orang / Bulan / Kegiatan','Orang / Hari',
            'Orang / Jam','Orang / Jam / Pelajaran','Orang / Kali','Orang / Kamar',
            'Orang / Kedatangan','Orang / Keg. / Bln','Orang / Kegiatan','Orang / Materi',
            'Orang / Paket / Pekerjaan','Orang / Perjalanan','Orang / PP','Orang / Sessi',
            'Orang / Session','Orang / Titik','Organisasi','Pack','Pail','Pak','Parpol',
            'Pasang','Pc','Pcs','Pekerjaan','Pelepah','Pendampingan','Per 100 Lembar',
            'Per Balok','Per Batang','Per Batang Pohon','Per Buku','Per Bulan','Per Bungkus',
            'Per Detik','Per Keping','Per Kotak','Per Liputan','Per Orang','Per Rim',
            'Per Ruang','Per Sampel','Per Tayang','Per Titik','Persen','Pert 100 Buah',
            'Pick Up','Porsi','Posyandu','Pot','Produk Hukum','Pulsa','Rean','Regu','Rim',
            'Roll','Roll Besar','Rupiah','RW','Sachet','Sampel','Sekolah','Semester',
            'Sesi','Set','Shift','Siklus','Siswa','Stel','Strip','Supp','Surat','Tablet',
            'Tabung','Tahun','Tangki (4000 Liter)','Tayang / Spot',
            'Tayang / Spot Durasi 30 Detik','Tempat','Titik','Titik Lampu','Ton','Triwulan',
            'Tube','Unit','Unit / Bulan','Unit / Pompa','Unit / Tahun','USK','VA','Vial',
            'Watt','Zak'
        ];

        const placeholders = satuanList.map((_, index) => `$${index + 1}`).join(', ');

        await queryRunner.query(
            `DELETE FROM "satuans" WHERE "satuan" IN (${placeholders})`,
            satuanList,
        );
    }
}
