import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedRekenings1763805006431 implements MigrationInterface {
    name = 'SeedRekenings1763805006431';

    private readonly rekenings = [
        { rekening_kode: '5', rekening_uraian: 'Belanja Daerah' },
        { rekening_kode: '5.1', rekening_uraian: 'Belanja Operasi' },
        { rekening_kode: '5.1.02', rekening_uraian: 'Belanja Barang dan Jasa' },
        { rekening_kode: '5.1.02.02', rekening_uraian: 'Belanja Jasa' },
        { rekening_kode: '5.1.02.02.08', rekening_uraian: 'Belanja Jasa Konsultansi Konstruksi' },
        { rekening_kode: '5.1.02.02.08.0001', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Arsitektur-Jasa Nasihat dan Pra Desain Arsitektural' },
        { rekening_kode: '5.1.02.02.08.0002', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Arsitektur-Jasa Desain Arsitektural' },
        { rekening_kode: '5.1.02.02.08.0003', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Arsitektur-Jasa Penilai Perawatan dan Kelayakan Bangunan Gedung' },
        { rekening_kode: '5.1.02.02.08.0004', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Arsitektur-Jasa Desain Interior' },
        { rekening_kode: '5.1.02.02.08.0005', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Arsitektur-Jasa Arsitektur Lainnya' },
        { rekening_kode: '5.1.02.02.08.0006', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Rekayasa-Jasa Nasihat dan Konsultansi Rekayasa Teknik' },
        { rekening_kode: '5.1.02.02.08.0007', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Rekayasa-Jasa Desain Rekayasa untuk Konstruksi Pondasi serta Struktur Bangunan' },
        { rekening_kode: '5.1.02.02.08.0008', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Rekayasa-Jasa Desain Rekayasa untuk Pekerjaan Teknik Sipil Air' },
        { rekening_kode: '5.1.02.02.08.0009', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Rekayasa-Jasa Desain Rekayasa untuk Pekerjaan Teknik Sipil Transportasi' },
        { rekening_kode: '5.1.02.02.08.0010', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Rekayasa-Jasa Desain Rekayasa untuk Pekerjaan Mekanikal dan Elektrikal dalam Bangunan' },
        { rekening_kode: '5.1.02.02.08.0011', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Rekayasa-Jasa Desain Rekayasa untuk Proses Industrial dan Produksi' },
        { rekening_kode: '5.1.02.02.08.0012', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Rekayasa-Jasa Nasihat dan Konsultansi Jasa Rekayasa Konstruksi' },
        { rekening_kode: '5.1.02.02.08.0013', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Rekayasa-Jasa Desain Rekayasa Lainnya' },
        { rekening_kode: '5.1.02.02.08.0014', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Penataan Ruang-Jasa Perencanaan dan Perancangan Perkotaan' },
        { rekening_kode: '5.1.02.02.08.0015', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Penataan Ruang-Jasa Perencanaan Wilayah' },
        { rekening_kode: '5.1.02.02.08.0016', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Penataan Ruang-Jasa Perencanaan dan Perancangan Lingkungan Bangunan dan Landscape' },
        { rekening_kode: '5.1.02.02.08.0017', rekening_uraian: 'Belanja Jasa Konsultansi Perencanaan Penataan Ruang-Pengembangan Pemanfaatan Ruang' },
        { rekening_kode: '5.1.02.02.08.0018', rekening_uraian: 'Belanja Jasa Konsultansi Pengawasan Arsitektur' },
        { rekening_kode: '5.1.02.02.08.0019', rekening_uraian: 'Belanja Jasa Konsultansi Pengawasan Rekayasa-Jasa Pengawas Pekerjaan Konstruksi Bangunan Gedung' },
        { rekening_kode: '5.1.02.02.08.0020', rekening_uraian: 'Belanja Jasa Konsultansi Pengawasan Rekayasa-Jasa Pengawas Pekerjaan Konstruksi Teknik Sipil Transportasi' },
        { rekening_kode: '5.1.02.02.08.0021', rekening_uraian: 'Belanja Jasa Konsultansi Pengawasan Rekayasa-Jasa Pengawas Pekerjaan Konstruksi Teknik Sipil Air' },
        { rekening_kode: '5.1.02.02.08.0022', rekening_uraian: 'Belanja Jasa Konsultansi Pengawasan Rekayasa-Jasa Pengawas Pekerjaan Konstruksi dan Instalasi Proses dan Fasilitas Industri' },
        { rekening_kode: '5.1.02.02.08.0023', rekening_uraian: 'Belanja Jasa Konsultansi Pengawasan Penataan Ruang' },
        { rekening_kode: '5.1.02.02.08.0024', rekening_uraian: 'Belanja Jasa Konsultansi Spesialis-Jasa Pembuatan Prospektus Geologi dan Geofisika' },
        { rekening_kode: '5.1.02.02.08.0025', rekening_uraian: 'Belanja Jasa Konsultansi Spesialis-Jasa Survei Bawah Tanah' },
        { rekening_kode: '5.1.02.02.08.0026', rekening_uraian: 'Belanja Jasa Konsultansi Spesialis-Jasa Survei Permukaan Tanah' },
        { rekening_kode: '5.1.02.02.08.0027', rekening_uraian: 'Belanja Jasa Konsultansi Spesialis-Jasa Pembuatan Peta' },
        { rekening_kode: '5.1.02.02.08.0028', rekening_uraian: 'Belanja Jasa Konsultansi Spesialis-Jasa Pengujian dan Analisa Komposisi dan Tingkat Kemurnian' },
        { rekening_kode: '5.1.02.02.08.0029', rekening_uraian: 'Belanja Jasa Konsultansi Spesialis-Jasa Pengujian dan Analisa Parameter Fisikal' },
        { rekening_kode: '5.1.02.02.08.0030', rekening_uraian: 'Belanja Jasa Konsultansi Spesialis-Jasa Pengujian dan Analisa Sistem Mekanikal dan Elektrikal' },
        { rekening_kode: '5.1.02.02.08.0031', rekening_uraian: 'Belanja Jasa Konsultansi Spesialis-Jasa Inspeksi Teknikal' },
        { rekening_kode: '5.1.02.02.08.0032', rekening_uraian: 'Belanja Jasa Konsultansi Lainnya-Jasa Konsultansi Lingkungan' },
        { rekening_kode: '5.1.02.02.08.0033', rekening_uraian: 'Belanja Jasa Konsultansi Lainnya-Jasa Konsultansi Estimasi Nilai Lahan dan Bangunan' },
        { rekening_kode: '5.1.02.02.08.0034', rekening_uraian: 'Belanja Jasa Konsultansi Lainnya-Jasa Manajemen Proyek Terkait Konstruksi Bangunan' },
        { rekening_kode: '5.1.02.02.08.0035', rekening_uraian: 'Belanja Jasa Konsultansi Lainnya-Jasa Manajemen Proyek Terkait Konstruksi Pekerjaan Teknik Sipil Transportasi' },
        { rekening_kode: '5.1.02.02.08.0036', rekening_uraian: 'Belanja Jasa Konsultansi Lainnya-Jasa Manajamen Proyek Terkait Konstruksi Pekerjaan Teknik Sipil Keairan' },
        { rekening_kode: '5.1.02.02.08.0037', rekening_uraian: 'Belanja Jasa Konsultansi Lainnya-Jasa Manajemen Proyek Terkait Konstruksi Pekerjaan Teknik Sipil Lainnya' },
        { rekening_kode: '5.1.02.02.08.0038', rekening_uraian: 'Belanja (null)' },
        { rekening_kode: '5.1.02.02.08.0039', rekening_uraian: 'Belanja Jasa Konsultansi Lainnya-Jasa Manajemen Proyek Terkait Konstruksi Pekerjaan Sistem Kendali Lalu Lintas' },
        { rekening_kode: '5.1.02.02.08.0040', rekening_uraian: 'Belanja Jasa Konsultansi Lainnya-Jasa Rekayasa (Engineering) Terpadu' },
        { rekening_kode: '5.1.02.03', rekening_uraian: 'Belanja Pemeliharaan' },
        { rekening_kode: '5.1.02.03.03', rekening_uraian: 'Belanja Pemeliharaan Gedung dan Bangunan' },
        { rekening_kode: '5.1.02.03.03.0001', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Kantor' },
        { rekening_kode: '5.1.02.03.03.0002', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gudang' },
        { rekening_kode: '5.1.02.03.03.0003', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung untuk Bengkel/Hanggar' },
        { rekening_kode: '5.1.02.03.03.0004', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Instalasi' },
        { rekening_kode: '5.1.02.03.03.0005', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Laboratorium' },
        { rekening_kode: '5.1.02.03.03.0006', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Kesehatan' },
        { rekening_kode: '5.1.02.03.03.0007', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Oseanarium/Observatorium' },
        { rekening_kode: '5.1.02.03.03.0008', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Tempat Ibadah' },
        { rekening_kode: '5.1.02.03.03.0009', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Tempat Pertemuan' },
        { rekening_kode: '5.1.02.03.03.0010', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Tempat Pendidikan' },
        { rekening_kode: '5.1.02.03.03.0011', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Tempat Olahraga' },
        { rekening_kode: '5.1.02.03.03.0012', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Pertokoan/Koperasi/Pasar' },
        { rekening_kode: '5.1.02.03.03.0013', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung untuk Pos Jaga' },
        { rekening_kode: '5.1.02.03.03.0014', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Garasi/Pool' },
        { rekening_kode: '5.1.02.03.03.0015', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Pemotong Hewan' },
        { rekening_kode: '5.1.02.03.03.0016', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Perpustakaan' },
        { rekening_kode: '5.1.02.03.03.0017', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Museum' },
        { rekening_kode: '5.1.02.03.03.0018', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Terminal/Pelabuhan/Bandara' },
        { rekening_kode: '5.1.02.03.03.0019', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Pengujian Kelaikan' },
        { rekening_kode: '5.1.02.03.03.0020', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Lembaga Pemasyarakatan' },
        { rekening_kode: '5.1.02.03.03.0021', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Rumah Tahanan' },
        { rekening_kode: '5.1.02.03.03.0022', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Krematorium' },
        { rekening_kode: '5.1.02.03.03.0023', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Pembakaran Bangkai Hewan' },
        { rekening_kode: '5.1.02.03.03.0024', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Tempat Persidangan' },
        { rekening_kode: '5.1.02.03.03.0025', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Terbuka' },
        { rekening_kode: '5.1.02.03.03.0026', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Penampung Sekam' },
        { rekening_kode: '5.1.02.03.03.0027', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Tempat Pelelangan Ikan (TPI)' },
        { rekening_kode: '5.1.02.03.03.0028', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Industri' },
        { rekening_kode: '5.1.02.03.03.0029', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Peternakan/Perikanan' },
        { rekening_kode: '5.1.02.03.03.0030', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Tempat Kerja Lainnya' },
        { rekening_kode: '5.1.02.03.03.0031', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Peralatan Geofisika' },
        { rekening_kode: '5.1.02.03.03.0032', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Fasilitas Umum' },
        { rekening_kode: '5.1.02.03.03.0033', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Parkir' },
        { rekening_kode: '5.1.02.03.03.0034', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Pabrik' },
        { rekening_kode: '5.1.02.03.03.0035', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Stasiun Bus' },
        { rekening_kode: '5.1.02.03.03.0036', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Taman' },
        { rekening_kode: '5.1.02.03.03.0037', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Kerja-Bangunan Gedung Tempat Kerja Lainnya' },
        { rekening_kode: '5.1.02.03.03.0038', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Rumah Negara Golongan I' },
        { rekening_kode: '5.1.02.03.03.0039', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Rumah Negara Golongan II' },
        { rekening_kode: '5.1.02.03.03.0040', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Rumah Negara Golongan III' },
        { rekening_kode: '5.1.02.03.03.0041', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Mess/Wisma/Bungalow/Tempat Peristirahatan' },
        { rekening_kode: '5.1.02.03.03.0042', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Asrama' },
        { rekening_kode: '5.1.02.03.03.0043', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Hotel' },
        { rekening_kode: '5.1.02.03.03.0044', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Motel' },
        { rekening_kode: '5.1.02.03.03.0045', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Flat/Rumah Susun' },
        { rekening_kode: '5.1.02.03.03.0046', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Rumah Negara dalam Proses Penggolongan' },
        { rekening_kode: '5.1.02.03.03.0047', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Panti Asuhan' },
        { rekening_kode: '5.1.02.03.03.0048', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Apartemen' },
        { rekening_kode: '5.1.02.03.03.0049', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Rumah Tidak Bersusun' },
        { rekening_kode: '5.1.02.03.03.0050', rekening_uraian: 'Belanja Pemeliharaan Bangunan Gedung-Bangunan Gedung Tempat Tinggal-Bangunan Gedung Tempat Tinggal Lainnya' },
        { rekening_kode: '5.1.02.03.03.0051', rekening_uraian: 'Belanja Pemeliharaan Monumen-Candi/Tugu Peringatan/Prasasti-Candi' },
        { rekening_kode: '5.1.02.03.03.0052', rekening_uraian: 'Belanja Pemeliharaan Monumen-Candi/Tugu Peringatan/Prasasti-Tugu' },
        { rekening_kode: '5.1.02.03.03.0053', rekening_uraian: 'Belanja Pemeliharaan Monumen-Candi/Tugu Peringatan/Prasasti-Bangunan Peninggalan' },
        { rekening_kode: '5.1.02.03.03.0054', rekening_uraian: 'Belanja Pemeliharaan Monumen-Candi/Tugu Peringatan/Prasasti-Candi/Tugu Peringatan/ Prasasti Lainnya' },
        { rekening_kode: '5.1.02.03.03.0055', rekening_uraian: 'Belanja Pemeliharaan Bangunan Menara-Bangunan Menara Perambuan-Bangunan Menara Perambuan Penerangan Pantai' },
        { rekening_kode: '5.1.02.03.03.0056', rekening_uraian: 'Belanja Pemeliharaan Bangunan Menara-Bangunan Menara Perambuan-Bangunan Perambuan Penerangan Pantai' },
        { rekening_kode: '5.1.02.03.03.0057', rekening_uraian: 'Belanja Pemeliharaan Bangunan Menara-Bangunan Menara Perambuan-Bangunan Menara Telekomunikasi' },
        { rekening_kode: '5.1.02.03.03.0058', rekening_uraian: 'Belanja Pemeliharaan Bangunan Menara-Bangunan Menara Perambuan-Bangunan Menara Pengawas' },
        { rekening_kode: '5.1.02.03.03.0059', rekening_uraian: 'Belanja Pemeliharaan Bangunan Menara-Bangunan Menara Perambuan-Bangunan Menara Perambuan Lainnya' },
        { rekening_kode: '5.1.02.03.03.0060', rekening_uraian: 'Belanja Pemeliharaan Tugu Titik Kontrol/Pasti-Tugu/Tanda Batas-Tugu/Tanda Batas Administrasi' },
        { rekening_kode: '5.1.02.03.03.0061', rekening_uraian: 'Belanja Pemeliharaan Tugu Titik Kontrol/Pasti- Tugu/Tanda Batas-Tugu/Tanda Jaring Kontrol Geodesi' },
        { rekening_kode: '5.1.02.03.03.0062', rekening_uraian: 'Belanja Pemeliharaan Tugu Titik Kontrol/Pasti- Tugu/Tanda Batas-Pilar/Tugu/Tanda Lainnya' },
        { rekening_kode: '5.1.02.03.03.0063', rekening_uraian: 'Belanja Pemeliharaan Tugu Titik Kontrol/Pasti-Tugu/Tanda Batas-Pagar' },
        { rekening_kode: '5.1.02.03.03.0064', rekening_uraian: 'Belanja Pemeliharaan Tugu Titik Kontrol/Pasti-Tugu/Tanda Batas-Tugu/Tanda Batas Lainnya' },
        { rekening_kode: '5.1.02.03.04', rekening_uraian: 'Belanja Pemeliharaan Jalan, Jaringan, dan Irigasi' },
        { rekening_kode: '5.1.02.03.04.0001', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Jalan Nasional' },
        { rekening_kode: '5.1.02.03.04.0002', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Jalan Provinsi' },
        { rekening_kode: '5.1.02.03.04.0003', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Jalan Kabupaten' },
        { rekening_kode: '5.1.02.03.04.0004', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Jalan Kota' },
        { rekening_kode: '5.1.02.03.04.0005', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Jalan Desa' },
        { rekening_kode: '5.1.02.03.04.0006', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Jalan Tol' },
        { rekening_kode: '5.1.02.03.04.0007', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Jalan Kereta Api' },
        { rekening_kode: '5.1.02.03.04.0008', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Landasan Pacu Pesawat Terbang' },
        { rekening_kode: '5.1.02.03.04.0009', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Jalan Khusus' },
        { rekening_kode: '5.1.02.03.04.0010', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jalan-Jalan Lainnya' },
        { rekening_kode: '5.1.02.03.04.0011', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan pada Jalan Nasional' },
        { rekening_kode: '5.1.02.03.04.0012', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan pada Jalan Provinsi' },
        { rekening_kode: '5.1.02.03.04.0013', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan pada Jalan Kabupaten' },
        { rekening_kode: '5.1.02.03.04.0014', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan pada Jalan Kota' },
        { rekening_kode: '5.1.02.03.04.0015', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan pada Jalan Desa' },
        { rekening_kode: '5.1.02.03.04.0016', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan pada Jalan Tol' },
        { rekening_kode: '5.1.02.03.04.0017', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan pada Jalan Kereta Api' },
        { rekening_kode: '5.1.02.03.04.0018', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan pada Landasan Pacu Pesawat Terbang' },
        { rekening_kode: '5.1.02.03.04.0019', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan pada Jalan Khusus' },
        { rekening_kode: '5.1.02.03.04.0020', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan Penyeberangan' },
        { rekening_kode: '5.1.02.03.04.0021', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan Labuh/Sandar pada Terminal' },
        { rekening_kode: '5.1.02.03.04.0022', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan Pengukur' },
        { rekening_kode: '5.1.02.03.04.0023', rekening_uraian: 'Belanja Pemeliharaan Jalan dan Jembatan-Jembatan-Jembatan Lainnya' },
        { rekening_kode: '5.1.02.03.04.0024', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Irigasi-Bangunan Waduk Irigasi' },
        { rekening_kode: '5.1.02.03.04.0025', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Irigasi-Bangunan Pengambilan Irigasi' },
        { rekening_kode: '5.1.02.03.04.0026', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Irigasi-Bangunan Pembawa Irigasi' },
        { rekening_kode: '5.1.02.03.04.0027', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Irigasi-Bangunan Pembuang Irigasi' },
        { rekening_kode: '5.1.02.03.04.0028', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Irigasi-Bangunan Pengaman Irigasi' },
        { rekening_kode: '5.1.02.03.04.0029', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Irigasi-Bangunan Pelengkap Irigasi' },
        { rekening_kode: '5.1.02.03.04.0030', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Irigasi-Bangunan Sawah Irigasi' },
        { rekening_kode: '5.1.02.03.04.0031', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Irigasi-Bangunan Air Irigasi Lainnya' },
        { rekening_kode: '5.1.02.03.04.0032', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengairan Pasang Surut-Bangunan Waduk Pasang Surut' },
        { rekening_kode: '5.1.02.03.04.0033', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengairan Pasang Surut-Bangunan Pengambilan Pasang Surut' },
        { rekening_kode: '5.1.02.03.04.0034', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengairan Pasang Surut-Bangunan Pembawa Pasang Surut' },
        { rekening_kode: '5.1.02.03.04.0035', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengairan Pasang Surut-Saluran Pembuang Pasang Surut' },
        { rekening_kode: '5.1.02.03.04.0036', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengairan Pasang Surut-Bangunan Pengaman Pasang Surut' },
        { rekening_kode: '5.1.02.03.04.0037', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengairan Pasang Surut-Bangunan Pelengkap Pasang Surut' },
        { rekening_kode: '5.1.02.03.04.0038', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengairan Pasang Surut-Bangunan Sawah Pasang Surut' },
        { rekening_kode: '5.1.02.03.04.0039', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengairan Pasang Surut-Bangunan Pengairan Pasang Surut Lainnya' },
        { rekening_kode: '5.1.02.03.04.0040', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Rawa dan Polder-Bangunan Waduk Pengembangan Rawa' },
        { rekening_kode: '5.1.02.03.04.0041', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Rawa dan Polder-Bangunan Pengambilan Pengembangan Rawa' },
        { rekening_kode: '5.1.02.03.04.0042', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Rawa dan Polder-Bangunan Pembawa Pengembangan Rawa' },
        { rekening_kode: '5.1.02.03.04.0043', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Rawa dan Polder-Bangunan Pembuang Pengembangan Rawa' },
        { rekening_kode: '5.1.02.03.04.0044', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Rawa dan Polder-Bangunan Pengaman Pengembangan Rawa' },
        { rekening_kode: '5.1.02.03.04.0045', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Rawa dan Polder-Bangunan Pelengkap Pengembangan Rawa' },
        { rekening_kode: '5.1.02.03.04.0046', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Rawa dan Polder-Bangunan Sawah Pengembangan Rawa' },
        { rekening_kode: '5.1.02.03.04.0047', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Rawa dan Polder-Bangunan Pengembangan Rawa dan Polder Lainnya' },
        { rekening_kode: '5.1.02.03.04.0048', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam-Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam' },
        { rekening_kode: '5.1.02.03.04.0049', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam-Bangunan Pengambilan Pengaman Sungai/Pantai' },
        { rekening_kode: '5.1.02.03.04.0050', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam-Bangunan Pembawa Pengaman Sungai/Pantai' },
        { rekening_kode: '5.1.02.03.04.0051', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam-Bangunan Pembuang Pengaman Sungai' },
        { rekening_kode: '5.1.02.03.04.0052', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam-Bangunan Pengaman Pengamanan Sungai/Pantai' },
        { rekening_kode: '5.1.02.03.04.0053', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam-Bangunan Pelengkap Pengaman Sungai' },
        { rekening_kode: '5.1.02.03.04.0054', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam-Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam Lainnya' },
        { rekening_kode: '5.1.02.03.04.0055', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Sumber Air dan Air Tanah-Bangunan Waduk Pengembangan Sumber Air' },
        { rekening_kode: '5.1.02.03.04.0056', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Sumber Air dan Air Tanah-Bangunan Pengambilan Pengembangan Sumber Air' },
        { rekening_kode: '5.1.02.03.04.0057', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Sumber Air dan Air Tanah-Bangunan Pembawa Pengembangan Sumber Air' },
        { rekening_kode: '5.1.02.03.04.0058', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Sumber Air dan Air Tanah-Bangunan Pembuang Pengembangan Sumber Air' },
        { rekening_kode: '5.1.02.03.04.0059', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Sumber Air dan Air Tanah-Bangunan Pengaman Pengembangan Sumber Air' },
        { rekening_kode: '5.1.02.03.04.0060', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Sumber Air dan Air Tanah-Bangunan Pelengkap Pengembangan Sumber Air' },
        { rekening_kode: '5.1.02.03.04.0061', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Sumber Air dan Air Tanah-Bangunan Sawah Irigasi Air Tanah' },
        { rekening_kode: '5.1.02.03.04.0062', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Pengembangan Sumber Air dan Air Tanah-Bangunan Pengembangan Sumber Air dan Air Tanah Lainnya' },
        { rekening_kode: '5.1.02.03.04.0063', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Bersih/Air Baku Lainnya-Bangunan Waduk Air Bersih/Air Baku' },
        { rekening_kode: '5.1.02.03.04.0064', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Bersih/Air Baku Lainnya-Bangunan Pengambilan Air Bersih/Air Baku' },
        { rekening_kode: '5.1.02.03.04.0065', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Bersih/Air Baku Lainnya-Bangunan Pembawa Air Bersih/Air Baku' },
        { rekening_kode: '5.1.02.03.04.0066', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Bersih/Air Baku Lainnya-Bangunan Pembuang Air Bersih/Air Baku' },
        { rekening_kode: '5.1.02.03.04.0067', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Bersih/Air Baku Lainnya-Bangunan Pelengkap Air Bersih/Air Baku' },
        { rekening_kode: '5.1.02.03.04.0068', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Bersih/Air Baku Lainnya-Bangunan Air Bersih/Air Baku Lainnya' },
        { rekening_kode: '5.1.02.03.04.0069', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Kotor-Bangunan Pembawa Air Kotor' },
        { rekening_kode: '5.1.02.03.04.0070', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Kotor-Bangunan Waduk Air Kotor' },
        { rekening_kode: '5.1.02.03.04.0071', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Kotor-Bangunan Pembuang Air Kotor' },
        { rekening_kode: '5.1.02.03.04.0072', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Kotor-Bangunan Pengaman Air Kotor' },
        { rekening_kode: '5.1.02.03.04.0073', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Kotor-Bangunan Pelengkap Air Kotor' },
        { rekening_kode: '5.1.02.03.04.0074', rekening_uraian: 'Belanja Pemeliharaan Bangunan Air-Bangunan Air Kotor-Bangunan Air Kotor Lainnya' },
        { rekening_kode: '5.1.02.03.04.0075', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Air Bersih/Air Baku-Instalasi Air Permukaan' },
        { rekening_kode: '5.1.02.03.04.0076', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Air Bersih/Air Baku-Instalasi Air Sumber/Mata Air' },
        { rekening_kode: '5.1.02.03.04.0077', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Air Bersih/Air Baku-Instalasi Air Tanah Dalam' },
        { rekening_kode: '5.1.02.03.04.0078', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Air Bersih/Air Baku-Instalasi Air Tanah Dangkal' },
        { rekening_kode: '5.1.02.03.04.0079', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Air Bersih/Air Baku-Instalasi Air Bersih/Air Baku Lainnya' },
        { rekening_kode: '5.1.02.03.04.0080', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Air Kotor-Instalasi Air Buangan Domestik' },
        { rekening_kode: '5.1.02.03.04.0081', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Air Kotor-Instalasi Air Buangan Industri' },
        { rekening_kode: '5.1.02.03.04.0082', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Air Kotor-Instalasi Air Buangan Pertanian' },
        { rekening_kode: '5.1.02.03.04.0083', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Air Kotor-Instalasi Air Kotor Lainnya' },
        { rekening_kode: '5.1.02.03.04.0084', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengolahan Sampah-Instalasi Pengolahan Sampah Organik' },
        { rekening_kode: '5.1.02.03.04.0085', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengolahan Sampah-Instalasi Pengolahan Sampah Non Organik' },
        { rekening_kode: '5.1.02.03.04.0086', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengolahan Sampah-Bangunan Penampung Sampah' },
        { rekening_kode: '5.1.02.03.04.0087', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengolahan Sampah-Instalasi Pengolahan Sampah Lainnya' },
        { rekening_kode: '5.1.02.03.04.0088', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengolahan Bahan Bangunan-Instalasi Pengolahan Bahan Bangunan Percontohan' },
        { rekening_kode: '5.1.02.03.04.0089', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengolahan Bahan Bangunan-Instalasi Pengolahan Bahan Bangunan Perintis' },
        { rekening_kode: '5.1.02.03.04.0090', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengolahan Bahan Bangunan-Instalasi Pengolahan Bahan Bangunan Terapan' },
        { rekening_kode: '5.1.02.03.04.0091', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengolahan Bahan Bangunan-Instalasi Pengolahan Bahan Bangunan Lainnya' },
        { rekening_kode: '5.1.02.03.04.0092', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Air (PLTA)' },
        { rekening_kode: '5.1.02.03.04.0093', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Diesel (PLTD)' },
        { rekening_kode: '5.1.02.03.04.0094', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Mikro Hidro (PLTM)' },
        { rekening_kode: '5.1.02.03.04.0095', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Angin (PLTAN)' },
        { rekening_kode: '5.1.02.03.04.0096', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Uap (PLTU)' },
        { rekening_kode: '5.1.02.03.04.0097', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Nuklir (PLTN)' },
        { rekening_kode: '5.1.02.03.04.0098', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Gas (PLTG)' },
        { rekening_kode: '5.1.02.03.04.0099', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Panas Bumi (PLTP)' },
        { rekening_kode: '5.1.02.03.04.0100', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Surya (PLTS)' },
        { rekening_kode: '5.1.02.03.04.0101', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Biogas (PLTB)' },
        { rekening_kode: '5.1.02.03.04.0102', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Tenaga Samudera/Gelombang Samudera' },
        { rekening_kode: '5.1.02.03.04.0103', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pembangkit Listrik-Instalasi Pembangkit Listrik Lainnya' },
        { rekening_kode: '5.1.02.03.04.0104', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Gardu Listrik-Instalasi Gardu Listrik Induk' },
        { rekening_kode: '5.1.02.03.04.0105', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Gardu Listrik-Instalasi Gardu Listrik Distribusi' },
        { rekening_kode: '5.1.02.03.04.0106', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Gardu Listrik-Instalasi Pusat Pengatur Listrik' },
        { rekening_kode: '5.1.02.03.04.0107', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Gardu Listrik-Instalasi Gardu Listrik Lainnya' },
        { rekening_kode: '5.1.02.03.04.0108', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pertahanan-Instalasi Pertahanan di Darat' },
        { rekening_kode: '5.1.02.03.04.0109', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pertahanan-Instalasi Pertahanan Lainnya' },
        { rekening_kode: '5.1.02.03.04.0110', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Gas-Instalasi Gardu Gas' },
        { rekening_kode: '5.1.02.03.04.0111', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Gas-Instalasi Jaringan Pipa Gas' },
        { rekening_kode: '5.1.02.03.04.0112', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Gas-Instalasi Pengolahan Gas' },
        { rekening_kode: '5.1.02.03.04.0113', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Gas-Instalasi Gas Lainnya' },
        { rekening_kode: '5.1.02.03.04.0114', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengaman-Instalasi Pengaman Penangkal Petir' },
        { rekening_kode: '5.1.02.03.04.0115', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengaman-Instalasi Reaktor Nuklir' },
        { rekening_kode: '5.1.02.03.04.0116', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengaman-Instalasi Pengolahan Limbah Radioaktif' },
        { rekening_kode: '5.1.02.03.04.0117', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Pengaman-Instalasi Pengaman Lainnya' },
        { rekening_kode: '5.1.02.03.04.0118', rekening_uraian: 'Belanja Pemeliharaan Instalasi-Instalasi Lain-Instalasi Lain' },
        { rekening_kode: '5.1.02.03.04.0119', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Air Minum-Jaringan Pembawa' },
        { rekening_kode: '5.1.02.03.04.0120', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Air Minum-Jaringan Induk Distribusi' },
        { rekening_kode: '5.1.02.03.04.0121', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Air Minum-Jaringan Cabang Distribusi' },
        { rekening_kode: '5.1.02.03.04.0122', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Air Minum-Jaringan Sambungan ke Rumah' },
        { rekening_kode: '5.1.02.03.04.0123', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Air Minum-Jaringan Air Minum Lainnya' },
        { rekening_kode: '5.1.02.03.04.0124', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Listrik-Jaringan Transmisi' },
        { rekening_kode: '5.1.02.03.04.0125', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Listrik-Jaringan Distribusi' },
        { rekening_kode: '5.1.02.03.04.0126', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Listrik-Jaringan Listrik Lainnya' },
        { rekening_kode: '5.1.02.03.04.0127', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Telepon-Jaringan Telepon di atas Tanah' },
        { rekening_kode: '5.1.02.03.04.0128', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Telepon-Jaringan Telepon di bawah Tanah' },
        { rekening_kode: '5.1.02.03.04.0129', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Telepon-Jaringan Telepon di dalam Air' },
        { rekening_kode: '5.1.02.03.04.0130', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Telepon-Jaringan dengan Media Udara' },
        { rekening_kode: '5.1.02.03.04.0131', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Telepon-Jaringan Telepon Lainnya' },
        { rekening_kode: '5.1.02.03.04.0132', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Gas-Jaringan Pipa Gas Transmisi' },
        { rekening_kode: '5.1.02.03.04.0133', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Gas-Jaringan Pipa Distribusi' },
        { rekening_kode: '5.1.02.03.04.0134', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Gas-Jaringan Pipa Dinas' },
        { rekening_kode: '5.1.02.03.04.0135', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Gas-Jaringan BBM' },
        { rekening_kode: '5.1.02.03.04.0136', rekening_uraian: 'Belanja Pemeliharaan Jaringan-Jaringan Gas-Jaringan Gas Lainnya' },
        { rekening_kode: '5.2', rekening_uraian: 'Belanja Modal' },
        { rekening_kode: '5.2.03', rekening_uraian: 'Belanja Modal Gedung dan Bangunan' },
        { rekening_kode: '5.2.03.01', rekening_uraian: 'Belanja Modal Bangunan Gedung' },
        { rekening_kode: '5.2.03.01.01', rekening_uraian: 'Belanja Modal Bangunan Gedung Tempat Kerja' },
        { rekening_kode: '5.2.03.01.01.0001', rekening_uraian: 'Belanja Modal Bangunan Gedung Kantor' },
        { rekening_kode: '5.2.03.01.01.0002', rekening_uraian: 'Belanja Modal Bangunan Gudang' },
        { rekening_kode: '5.2.03.01.01.0003', rekening_uraian: 'Belanja Modal Bangunan Gedung untuk Bengkel/Hanggar' },
        { rekening_kode: '5.2.03.01.01.0004', rekening_uraian: 'Belanja Modal Bangunan Gedung Instalasi' },
        { rekening_kode: '5.2.03.01.01.0005', rekening_uraian: 'Belanja Modal Bangunan Gedung Laboratorium' },
        { rekening_kode: '5.2.03.01.01.0006', rekening_uraian: 'Belanja Modal Bangunan Kesehatan' },
        { rekening_kode: '5.2.03.01.01.0007', rekening_uraian: 'Belanja Modal Bangunan Oseanarium/Observatorium' },
        { rekening_kode: '5.2.03.01.01.0008', rekening_uraian: 'Belanja Modal Bangunan Gedung Tempat Ibadah' },
        { rekening_kode: '5.2.03.01.01.0009', rekening_uraian: 'Belanja Modal Bangunan Gedung Tempat Pertemuan' },
        { rekening_kode: '5.2.03.01.01.0010', rekening_uraian: 'Belanja Modal Bangunan Gedung Tempat Pendidikan' },
        { rekening_kode: '5.2.03.01.01.0011', rekening_uraian: 'Belanja Modal Bangunan Gedung Tempat Olahraga' },
        { rekening_kode: '5.2.03.01.01.0012', rekening_uraian: 'Belanja Modal Bangunan Gedung Pertokoan/Koperasi/Pasar' },
        { rekening_kode: '5.2.03.01.01.0013', rekening_uraian: 'Belanja Modal Bangunan Gedung untuk Pos Jaga' },
        { rekening_kode: '5.2.03.01.01.0014', rekening_uraian: 'Belanja Modal Bangunan Gedung Garasi/Pool' },
        { rekening_kode: '5.2.03.01.01.0015', rekening_uraian: 'Belanja Modal Bangunan Gedung Pemotong Hewan' },
        { rekening_kode: '5.2.03.01.01.0016', rekening_uraian: 'Belanja Modal Bangunan Gedung Perpustakaan' },
        { rekening_kode: '5.2.03.01.01.0017', rekening_uraian: 'Belanja Modal Bangunan Gedung Museum' },
        { rekening_kode: '5.2.03.01.01.0018', rekening_uraian: 'Belanja Modal Bangunan Gedung Terminal/Pelabuhan/Bandara' },
        { rekening_kode: '5.2.03.01.01.0019', rekening_uraian: 'Belanja Modal Bangunan Pengujian Kelaikan' },
        { rekening_kode: '5.2.03.01.01.0020', rekening_uraian: 'Belanja Modal Bangunan Gedung Lembaga Pemasyarakatan' },
        { rekening_kode: '5.2.03.01.01.0021', rekening_uraian: 'Belanja Modal Bangunan Rumah Tahanan' },
        { rekening_kode: '5.2.03.01.01.0022', rekening_uraian: 'Belanja Modal Bangunan Gedung Krematorium' },
        { rekening_kode: '5.2.03.01.01.0023', rekening_uraian: 'Belanja Modal Bangunan Pembakaran Bangkai Hewan' },
        { rekening_kode: '5.2.03.01.01.0024', rekening_uraian: 'Belanja Modal Bangunan Tempat Persidangan' },
        { rekening_kode: '5.2.03.01.01.0025', rekening_uraian: 'Belanja Modal Bangunan Terbuka' },
        { rekening_kode: '5.2.03.01.01.0026', rekening_uraian: 'Belanja Modal Bangunan Penampung Sekam' },
        { rekening_kode: '5.2.03.01.01.0027', rekening_uraian: 'Belanja Modal Bangunan Tempat Pelelangan Ikan (TPI)' },
        { rekening_kode: '5.2.03.01.01.0028', rekening_uraian: 'Belanja Modal Bangunan Industri' },
        { rekening_kode: '5.2.03.01.01.0029', rekening_uraian: 'Belanja Modal Bangunan Peternakan/Perikanan' },
        { rekening_kode: '5.2.03.01.01.0030', rekening_uraian: 'Belanja Modal Bangunan Gedung Tempat Kerja Lainnya' },
        { rekening_kode: '5.2.03.01.01.0031', rekening_uraian: 'Belanja Modal Bangunan Peralatan Geofisika' },
        { rekening_kode: '5.2.03.01.01.0032', rekening_uraian: 'Belanja Modal Bangunan Fasilitas Umum' },
        { rekening_kode: '5.2.03.01.01.0033', rekening_uraian: 'Belanja Modal Bangunan Parkir' },
        { rekening_kode: '5.2.03.01.01.0034', rekening_uraian: 'Belanja Modal Bangunan Gedung Pabrik' },
        { rekening_kode: '5.2.03.01.01.0035', rekening_uraian: 'Belanja Modal Bangunan Stasiun Bus' },
        { rekening_kode: '5.2.03.01.01.0036', rekening_uraian: 'Belanja Modal Taman' },
        { rekening_kode: '5.2.03.01.01.0037', rekening_uraian: 'Belanja Modal Bangunan Gedung Tempat Kerja Lainnya' },
        { rekening_kode: '5.2.03.01.02', rekening_uraian: 'Belanja Modal Bangunan Gedung Tempat Tinggal' },
        { rekening_kode: '5.2.03.01.02.0001', rekening_uraian: 'Belanja Modal Rumah Negara Golongan I' },
        { rekening_kode: '5.2.03.01.02.0002', rekening_uraian: 'Belanja Modal Rumah Negara Golongan II' },
        { rekening_kode: '5.2.03.01.02.0003', rekening_uraian: 'Belanja Modal Rumah Negara Golongan III' },
        { rekening_kode: '5.2.03.01.02.0004', rekening_uraian: 'Belanja Modal Mess/Wisma/Bungalow/Tempat Peristirahatan' },
        { rekening_kode: '5.2.03.01.02.0005', rekening_uraian: 'Belanja Modal Asrama' },
        { rekening_kode: '5.2.03.01.02.0006', rekening_uraian: 'Belanja Modal Hotel' },
        { rekening_kode: '5.2.03.01.02.0007', rekening_uraian: 'Belanja Modal Motel' },
        { rekening_kode: '5.2.03.01.02.0008', rekening_uraian: 'Belanja Modal Flat/Rumah Susun' },
        { rekening_kode: '5.2.03.01.02.0009', rekening_uraian: 'Belanja Modal Rumah Negara dalam Proses Penggolongan' },
        { rekening_kode: '5.2.03.01.02.0010', rekening_uraian: 'Belanja Modal Panti Asuhan' },
        { rekening_kode: '5.2.03.01.02.0011', rekening_uraian: 'Belanja Modal Apartemen' },
        { rekening_kode: '5.2.03.01.02.0012', rekening_uraian: 'Belanja Modal Rumah Tidak Bersusun' },
        { rekening_kode: '5.2.03.01.02.0013', rekening_uraian: 'Belanja Modal Bangunan Gedung Tempat Tinggal Lainnya' },
        { rekening_kode: '5.2.03.02', rekening_uraian: 'Belanja Modal Monumen' },
        { rekening_kode: '5.2.03.02.01', rekening_uraian: 'Belanja Modal Candi/Tugu Peringatan/Prasasti' },
        { rekening_kode: '5.2.03.02.01.0001', rekening_uraian: 'Belanja Modal Candi' },
        { rekening_kode: '5.2.03.02.01.0002', rekening_uraian: 'Belanja Modal Tugu' },
        { rekening_kode: '5.2.03.02.01.0003', rekening_uraian: 'Belanja Modal Bangunan Peninggalan' },
        { rekening_kode: '5.2.03.02.01.0004', rekening_uraian: 'Belanja Modal Candi/Tugu Peringatan/Prasasti Lainnya' },
        { rekening_kode: '5.2.03.03', rekening_uraian: 'Belanja Modal Bangunan Menara' },
        { rekening_kode: '5.2.03.03.01', rekening_uraian: 'Belanja Modal Bangunan Menara Perambuan' },
        { rekening_kode: '5.2.03.03.01.0001', rekening_uraian: 'Belanja Modal Bangunan Menara Perambuan Penerangan Pantai' },
        { rekening_kode: '5.2.03.03.01.0002', rekening_uraian: 'Belanja Modal Bangunan Perambuan Penerangan Pantai' },
        { rekening_kode: '5.2.03.03.01.0003', rekening_uraian: 'Belanja Modal Bangunan Menara Telekomunikasi' },
        { rekening_kode: '5.2.03.03.01.0004', rekening_uraian: 'Belanja Modal Bangunan Menara Pengawas' },
        { rekening_kode: '5.2.03.03.01.0005', rekening_uraian: 'Belanja Modal Bangunan Menara Perambuan Lainnya' },
        { rekening_kode: '5.2.03.04', rekening_uraian: 'Belanja Modal Tugu Titik Kontrol/Pasti' },
        { rekening_kode: '5.2.03.04.01', rekening_uraian: 'Belanja Modal Tugu/Tanda Batas' },
        { rekening_kode: '5.2.03.04.01.0001', rekening_uraian: 'Belanja Modal Tugu/Tanda Batas Administrasi' },
        { rekening_kode: '5.2.03.04.01.0002', rekening_uraian: 'Belanja Modal Tugu/Tanda Jaring Kontrol Geodesi' },
        { rekening_kode: '5.2.03.04.01.0003', rekening_uraian: 'Belanja Modal Pilar/Tugu/Tanda Lainnya' },
        { rekening_kode: '5.2.03.04.01.0004', rekening_uraian: 'Belanja Modal Pagar' },
        { rekening_kode: '5.2.03.04.01.0005', rekening_uraian: 'Belanja Modal Tugu/Tanda Batas Lainnya' },
        { rekening_kode: '5.2.03.99', rekening_uraian: 'Belanja Modal Gedung dan Bangunan BLUD' },
        { rekening_kode: '5.2.03.99.99', rekening_uraian: 'Belanja Modal Gedung dan Bangunan BLUD' },
        { rekening_kode: '5.2.03.99.99.9999', rekening_uraian: 'Belanja Modal Gedung dan Bangunan BLUD' },
        { rekening_kode: '5.2.04', rekening_uraian: 'Belanja Modal Jalan, Jaringan, dan Irigasi' },
        { rekening_kode: '5.2.04.01', rekening_uraian: 'Belanja Modal Jalan dan Jembatan' },
        { rekening_kode: '5.2.04.01.01', rekening_uraian: 'Belanja Modal Jalan' },
        { rekening_kode: '5.2.04.01.01.0001', rekening_uraian: 'Belanja Modal Jalan Nasional' },
        { rekening_kode: '5.2.04.01.01.0002', rekening_uraian: 'Belanja Modal Jalan Provinsi' },
        { rekening_kode: '5.2.04.01.01.0003', rekening_uraian: 'Belanja Modal Jalan Kabupaten' },
        { rekening_kode: '5.2.04.01.01.0004', rekening_uraian: 'Belanja Modal Jalan Kota' },
        { rekening_kode: '5.2.04.01.01.0005', rekening_uraian: 'Belanja Modal Jalan Desa' },
        { rekening_kode: '5.2.04.01.01.0006', rekening_uraian: 'Belanja Modal Jalan Tol' },
        { rekening_kode: '5.2.04.01.01.0007', rekening_uraian: 'Belanja Modal Jalan Kereta Api' },
        { rekening_kode: '5.2.04.01.01.0008', rekening_uraian: 'Belanja Modal Landasan Pacu Pesawat Terbang' },
        { rekening_kode: '5.2.04.01.01.0009', rekening_uraian: 'Belanja Modal Jalan Khusus' },
        { rekening_kode: '5.2.04.01.01.0010', rekening_uraian: 'Belanja Modal Jalan Lainnya' },
        { rekening_kode: '5.2.04.01.02', rekening_uraian: 'Belanja Modal Jembatan' },
        { rekening_kode: '5.2.04.01.02.0001', rekening_uraian: 'Belanja Modal Jembatan pada Jalan Nasional' },
        { rekening_kode: '5.2.04.01.02.0002', rekening_uraian: 'Belanja Modal Jembatan pada Jalan Provinsi' },
        { rekening_kode: '5.2.04.01.02.0003', rekening_uraian: 'Belanja Modal Jembatan pada Jalan Kabupaten' },
        { rekening_kode: '5.2.04.01.02.0004', rekening_uraian: 'Belanja Modal Jembatan pada Jalan Kota' },
        { rekening_kode: '5.2.04.01.02.0005', rekening_uraian: 'Belanja Modal Jembatan pada Jalan Desa' },
        { rekening_kode: '5.2.04.01.02.0006', rekening_uraian: 'Belanja Modal Jembatan pada Jalan Tol' },
        { rekening_kode: '5.2.04.01.02.0007', rekening_uraian: 'Belanja Modal Jembatan pada Jalan Kereta Api' },
        { rekening_kode: '5.2.04.01.02.0008', rekening_uraian: 'Belanja Modal Jembatan pada Landasan Pacu Pesawat Terbang' },
        { rekening_kode: '5.2.04.01.02.0009', rekening_uraian: 'Belanja Modal Jembatan pada Jalan Khusus' },
        { rekening_kode: '5.2.04.01.02.0010', rekening_uraian: 'Belanja Modal Jembatan Penyeberangan' },
        { rekening_kode: '5.2.04.01.02.0011', rekening_uraian: 'Belanja Modal Jembatan Labuh/Sandar pada Terminal' },
        { rekening_kode: '5.2.04.01.02.0012', rekening_uraian: 'Belanja Modal Jembatan Pengukur' },
        { rekening_kode: '5.2.04.01.02.0013', rekening_uraian: 'Belanja Modal Jembatan Lainnya' },
        { rekening_kode: '5.2.04.02', rekening_uraian: 'Belanja Modal Bangunan Air' },
        { rekening_kode: '5.2.04.02.01', rekening_uraian: 'Belanja Modal Bangunan Air Irigasi' },
        { rekening_kode: '5.2.04.02.01.0001', rekening_uraian: 'Belanja Modal Bangunan Waduk Irigasi' },
        { rekening_kode: '5.2.04.02.01.0002', rekening_uraian: 'Belanja Modal Bangunan Pengambilan Irigasi' },
        { rekening_kode: '5.2.04.02.01.0003', rekening_uraian: 'Belanja Modal Bangunan Pembawa Irigasi' },
        { rekening_kode: '5.2.04.02.01.0004', rekening_uraian: 'Belanja Modal Bangunan Pembuang Irigasi' },
        { rekening_kode: '5.2.04.02.01.0005', rekening_uraian: 'Belanja Modal Bangunan Pengaman Irigasi' },
        { rekening_kode: '5.2.04.02.01.0006', rekening_uraian: 'Belanja Modal Bangunan Pelengkap Irigasi' },
        { rekening_kode: '5.2.04.02.01.0007', rekening_uraian: 'Belanja Modal Bangunan Sawah Irigasi' },
        { rekening_kode: '5.2.04.02.01.0008', rekening_uraian: 'Belanja Modal Bangunan Air Irigasi Lainnya' },
        { rekening_kode: '5.2.04.02.02', rekening_uraian: 'Belanja Modal Bangunan Pengairan Pasang Surut' },
        { rekening_kode: '5.2.04.02.02.0001', rekening_uraian: 'Belanja Modal Bangunan Waduk Pasang Surut' },
        { rekening_kode: '5.2.04.02.02.0002', rekening_uraian: 'Belanja Modal Bangunan Pengambilan Pasang Surut' },
        { rekening_kode: '5.2.04.02.02.0003', rekening_uraian: 'Belanja Modal Bangunan Pembawa Pasang Surut' },
        { rekening_kode: '5.2.04.02.02.0004', rekening_uraian: 'Belanja Modal Saluran Pembuang Pasang Surut' },
        { rekening_kode: '5.2.04.02.02.0005', rekening_uraian: 'Belanja Modal Bangunan Pengaman Pasang Surut' },
        { rekening_kode: '5.2.04.02.02.0006', rekening_uraian: 'Belanja Modal Bangunan Pelengkap Pasang Surut' },
        { rekening_kode: '5.2.04.02.02.0007', rekening_uraian: 'Belanja Modal Bangunan Sawah Pasang Surut' },
        { rekening_kode: '5.2.04.02.02.0008', rekening_uraian: 'Belanja Modal Bangunan Pengairan Pasang Surut Lainnya' },
        { rekening_kode: '5.2.04.02.03', rekening_uraian: 'Belanja Modal Bangunan Pengembangan Rawa dan Polder' },
        { rekening_kode: '5.2.04.02.03.0001', rekening_uraian: 'Belanja Modal Bangunan Waduk Pengembangan Rawa' },
        { rekening_kode: '5.2.04.02.03.0002', rekening_uraian: 'Belanja Modal Bangunan Pengambilan Pengembangan Rawa' },
        { rekening_kode: '5.2.04.02.03.0003', rekening_uraian: 'Belanja Modal Bangunan Pembawa Pengembangan Rawa' },
        { rekening_kode: '5.2.04.02.03.0004', rekening_uraian: 'Belanja Modal Bangunan Pembuang Pengembangan Rawa' },
        { rekening_kode: '5.2.04.02.03.0005', rekening_uraian: 'Belanja Modal Bangunan Pengaman Pengembangan Rawa' },
        { rekening_kode: '5.2.04.02.03.0006', rekening_uraian: 'Belanja Modal Bangunan Pelengkap Pengembangan Rawa' },
        { rekening_kode: '5.2.04.02.03.0007', rekening_uraian: 'Belanja Modal Bangunan Sawah Pengembangan Rawa' },
        { rekening_kode: '5.2.04.02.03.0008', rekening_uraian: 'Belanja Modal Bangunan Pengembangan Rawa dan Polder Lainnya' },
        { rekening_kode: '5.2.04.02.04', rekening_uraian: 'Belanja Modal Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam' },
        { rekening_kode: '5.2.04.02.04.0001', rekening_uraian: 'Belanja Modal Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam' },
        { rekening_kode: '5.2.04.02.04.0002', rekening_uraian: 'Belanja Modal Bangunan Pengambilan Pengaman Sungai/Pantai' },
        { rekening_kode: '5.2.04.02.04.0003', rekening_uraian: 'Belanja Modal Bangunan Pembawa Pengaman Sungai/Pantai' },
        { rekening_kode: '5.2.04.02.04.0004', rekening_uraian: 'Belanja Modal Bangunan Pembuang Pengaman Sungai' },
        { rekening_kode: '5.2.04.02.04.0005', rekening_uraian: 'Belanja Modal Bangunan Pengaman Pengamanan Sungai/Pantai' },
        { rekening_kode: '5.2.04.02.04.0006', rekening_uraian: 'Belanja Modal Bangunan Pelengkap Pengaman Sungai' },
        { rekening_kode: '5.2.04.02.04.0007', rekening_uraian: 'Belanja Modal Bangunan Pengaman Sungai/Pantai dan Penanggulangan Bencana Alam Lainnya' },
        { rekening_kode: '5.2.04.02.05', rekening_uraian: 'Belanja Modal Bangunan Pengembangan Sumber Air dan Air Tanah' },
        { rekening_kode: '5.2.04.02.05.0001', rekening_uraian: 'Belanja Modal Bangunan Waduk Pengembangan Sumber Air' },
        { rekening_kode: '5.2.04.02.05.0002', rekening_uraian: 'Belanja Modal Bangunan Pengambilan Pengembangan Sumber Air' },
        { rekening_kode: '5.2.04.02.05.0003', rekening_uraian: 'Belanja Modal Bangunan Pembawa Pengembangan Sumber Air' },
        { rekening_kode: '5.2.04.02.05.0004', rekening_uraian: 'Belanja Modal Bangunan Pembuang Pengembangan Sumber Air' },
        { rekening_kode: '5.2.04.02.05.0005', rekening_uraian: 'Belanja Modal Bangunan Pengaman Pengembangan Sumber Air' },
        { rekening_kode: '5.2.04.02.05.0006', rekening_uraian: 'Belanja Modal Bangunan Pelengkap Pengembangan Sumber Air' },
        { rekening_kode: '5.2.04.02.05.0007', rekening_uraian: 'Belanja Modal Bangunan Sawah Irigasi Air Tanah' },
        { rekening_kode: '5.2.04.02.05.0008', rekening_uraian: 'Belanja Modal Bangunan Pengembangan Sumber Air dan Air Tanah Lainnya' },
        { rekening_kode: '5.2.04.02.06', rekening_uraian: 'Belanja Modal Bangunan Air Bersih/Air Baku' },
        { rekening_kode: '5.2.04.02.06.0001', rekening_uraian: 'Belanja Modal Bangunan Waduk Air Bersih/Air Baku' },
        { rekening_kode: '5.2.04.02.06.0002', rekening_uraian: 'Belanja Modal Bangunan Pengambilan Air Bersih/Air Baku' },
        { rekening_kode: '5.2.04.02.06.0003', rekening_uraian: 'Belanja Modal Bangunan Pembawa Air Bersih/Air Baku' },
        { rekening_kode: '5.2.04.02.06.0004', rekening_uraian: 'Belanja Modal Bangunan Pembuang Air Bersih/Air Baku' },
        { rekening_kode: '5.2.04.02.06.0005', rekening_uraian: 'Belanja Modal Bangunan Pelengkap Air Bersih/Air Baku' },
        { rekening_kode: '5.2.04.02.06.0006', rekening_uraian: 'Belanja Modal Bangunan Air Bersih/Air Baku Lainnya' },
        { rekening_kode: '5.2.04.02.07', rekening_uraian: 'Belanja Modal Bangunan Air Kotor' },
        { rekening_kode: '5.2.04.02.07.0001', rekening_uraian: 'Belanja Modal Bangunan Pembawa Air Kotor' },
        { rekening_kode: '5.2.04.02.07.0002', rekening_uraian: 'Belanja Modal Bangunan Waduk Air Kotor' },
        { rekening_kode: '5.2.04.02.07.0003', rekening_uraian: 'Belanja Modal Bangunan Pembuang Air Kotor' },
        { rekening_kode: '5.2.04.02.07.0004', rekening_uraian: 'Belanja Modal Bangunan Pengaman Air Kotor' },
        { rekening_kode: '5.2.04.02.07.0005', rekening_uraian: 'Belanja Modal Bangunan Pelengkap Air Kotor' },
        { rekening_kode: '5.2.04.02.07.0006', rekening_uraian: 'Belanja Modal Bangunan Air Kotor Lainnya' },
        { rekening_kode: '5.2.04.03', rekening_uraian: 'Belanja Modal Instalasi' },
        { rekening_kode: '5.2.04.03.01', rekening_uraian: 'Belanja Modal Instalasi Air Bersih/Air Baku' },
        { rekening_kode: '5.2.04.03.01.0001', rekening_uraian: 'Belanja Modal Instalasi Air Permukaan' },
        { rekening_kode: '5.2.04.03.01.0002', rekening_uraian: 'Belanja Modal Instalasi Air Sumber/Mata Air' },
        { rekening_kode: '5.2.04.03.01.0003', rekening_uraian: 'Belanja Modal Instalasi Air Tanah Dalam' },
        { rekening_kode: '5.2.04.03.01.0004', rekening_uraian: 'Belanja Modal Instalasi Air Tanah Dangkal' },
        { rekening_kode: '5.2.04.03.01.0005', rekening_uraian: 'Belanja Modal Instalasi Air Bersih/Air Baku Lainnya' },
        { rekening_kode: '5.2.04.03.02', rekening_uraian: 'Belanja Modal Instalasi Air Kotor' },
        { rekening_kode: '5.2.04.03.02.0001', rekening_uraian: 'Belanja Modal Instalasi Air Buangan Domestik' },
        { rekening_kode: '5.2.04.03.02.0002', rekening_uraian: 'Belanja Modal Instalasi Air Buangan Industri' },
        { rekening_kode: '5.2.04.03.02.0003', rekening_uraian: 'Belanja Modal Instalasi Air Buangan Pertanian' },
        { rekening_kode: '5.2.04.03.02.0004', rekening_uraian: 'Belanja Modal Instalasi Air Kotor Lainnya' },
        { rekening_kode: '5.2.04.03.03', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Sampah' },
        { rekening_kode: '5.2.04.03.03.0001', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Sampah Organik' },
        { rekening_kode: '5.2.04.03.03.0002', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Sampah Non Organik' },
        { rekening_kode: '5.2.04.03.03.0003', rekening_uraian: 'Belanja Modal Bangunan Penampung Sampah' },
        { rekening_kode: '5.2.04.03.03.0004', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Sampah Lainnya' },
        { rekening_kode: '5.2.04.03.04', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Bahan Bangunan' },
        { rekening_kode: '5.2.04.03.04.0001', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Bahan Bangunan Percontohan' },
        { rekening_kode: '5.2.04.03.04.0002', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Bahan Bangunan Perintis' },
        { rekening_kode: '5.2.04.03.04.0003', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Bahan Bangunan Terapan' },
        { rekening_kode: '5.2.04.03.04.0004', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Bahan Bangunan Lainnya' },
        { rekening_kode: '5.2.04.03.05', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik' },
        { rekening_kode: '5.2.04.03.05.0001', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Air (PLTA)' },
        { rekening_kode: '5.2.04.03.05.0002', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Diesel (PLTD)' },
        { rekening_kode: '5.2.04.03.05.0003', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Mikro Hidro (PLTM)' },
        { rekening_kode: '5.2.04.03.05.0004', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Angin (PLTAN)' },
        { rekening_kode: '5.2.04.03.05.0005', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Uap (PLTU)' },
        { rekening_kode: '5.2.04.03.05.0006', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Nuklir (PLTN)' },
        { rekening_kode: '5.2.04.03.05.0007', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Gas (PLTG)' },
        { rekening_kode: '5.2.04.03.05.0008', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Panas Bumi (PLTP)' },
        { rekening_kode: '5.2.04.03.05.0009', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Surya (PLTS)' },
        { rekening_kode: '5.2.04.03.05.0010', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Biogas (PLTB)' },
        { rekening_kode: '5.2.04.03.05.0011', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Tenaga Samudera/Gelombang Samudera' },
        { rekening_kode: '5.2.04.03.05.0012', rekening_uraian: 'Belanja Modal Instalasi Pembangkit Listrik Lainnya' },
        { rekening_kode: '5.2.04.03.06', rekening_uraian: 'Belanja Modal Instalasi Gardu Listrik' },
        { rekening_kode: '5.2.04.03.06.0001', rekening_uraian: 'Belanja Modal Instalasi Gardu Listrik Induk' },
        { rekening_kode: '5.2.04.03.06.0002', rekening_uraian: 'Belanja Modal Instalasi Gardu Listrik Distribusi' },
        { rekening_kode: '5.2.04.03.06.0003', rekening_uraian: 'Belanja Modal Instalasi Pusat Pengatur Listrik' },
        { rekening_kode: '5.2.04.03.06.0004', rekening_uraian: 'Belanja Modal Instalasi Gardu Listrik Lainnya' },
        { rekening_kode: '5.2.04.03.07', rekening_uraian: 'Belanja Modal Instalasi Pertahanan' },
        { rekening_kode: '5.2.04.03.07.0001', rekening_uraian: 'Belanja Modal Instalasi Pertahanan di Darat' },
        { rekening_kode: '5.2.04.03.07.0002', rekening_uraian: 'Belanja Modal Instalasi Pertahanan Lainnya' },
        { rekening_kode: '5.2.04.03.08', rekening_uraian: 'Belanja Modal Instalasi Gas' },
        { rekening_kode: '5.2.04.03.08.0001', rekening_uraian: 'Belanja Modal Instalasi Gardu Gas' },
        { rekening_kode: '5.2.04.03.08.0002', rekening_uraian: 'Belanja Modal Instalasi Jaringan Pipa Gas' },
        { rekening_kode: '5.2.04.03.08.0003', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Gas' },
        { rekening_kode: '5.2.04.03.08.0004', rekening_uraian: 'Belanja Modal Instalasi Gas Lainnya' },
        { rekening_kode: '5.2.04.03.09', rekening_uraian: 'Belanja Modal Instalasi Pengaman' },
        { rekening_kode: '5.2.04.03.09.0001', rekening_uraian: 'Belanja Modal Instalasi Pengaman Penangkal Petir' },
        { rekening_kode: '5.2.04.03.09.0002', rekening_uraian: 'Belanja Modal Instalasi Reaktor Nuklir' },
        { rekening_kode: '5.2.04.03.09.0003', rekening_uraian: 'Belanja Modal Instalasi Pengolahan Limbah Radioaktif' },
        { rekening_kode: '5.2.04.03.09.0004', rekening_uraian: 'Belanja Modal Instalasi Pengaman Lainnya' },
        { rekening_kode: '5.2.04.03.10', rekening_uraian: 'Belanja Modal Instalasi Lain' },
        { rekening_kode: '5.2.04.03.10.0001', rekening_uraian: 'Belanja Modal Instalasi Lain' },
        { rekening_kode: '5.2.04.04', rekening_uraian: 'Belanja Modal Jaringan' },
        { rekening_kode: '5.2.04.04.01', rekening_uraian: 'Belanja Modal Jaringan Air Minum' },
        { rekening_kode: '5.2.04.04.01.0001', rekening_uraian: 'Belanja Modal Jaringan Pembawa' },
        { rekening_kode: '5.2.04.04.01.0002', rekening_uraian: 'Belanja Modal Jaringan Induk Distribusi' },
        { rekening_kode: '5.2.04.04.01.0003', rekening_uraian: 'Belanja Modal Jaringan Cabang Distribusi' },
        { rekening_kode: '5.2.04.04.01.0004', rekening_uraian: 'Belanja Modal Jaringan Sambungan ke Rumah' },
        { rekening_kode: '5.2.04.04.01.0005', rekening_uraian: 'Belanja Modal Jaringan Air Minum Lainnya' },
        { rekening_kode: '5.2.04.04.02', rekening_uraian: 'Belanja Modal Jaringan Listrik' },
        { rekening_kode: '5.2.04.04.02.0001', rekening_uraian: 'Belanja Modal Jaringan Transmisi' },
        { rekening_kode: '5.2.04.04.02.0002', rekening_uraian: 'Belanja Modal Jaringan Distribusi' },
        { rekening_kode: '5.2.04.04.02.0003', rekening_uraian: 'Belanja Modal Jaringan Listrik Lainnya' },
        { rekening_kode: '5.2.04.04.03', rekening_uraian: 'Belanja Modal Jaringan Telepon' },
        { rekening_kode: '5.2.04.04.03.0001', rekening_uraian: 'Belanja Modal Jaringan Telepon di atas Tanah' },
        { rekening_kode: '5.2.04.04.03.0002', rekening_uraian: 'Belanja Modal Jaringan Telepon di bawah Tanah' },
        { rekening_kode: '5.2.04.04.03.0003', rekening_uraian: 'Belanja Modal Jaringan Telepon di dalam Air' },
        { rekening_kode: '5.2.04.04.03.0004', rekening_uraian: 'Belanja Modal Jaringan dengan Media Udara' },
        { rekening_kode: '5.2.04.04.03.0005', rekening_uraian: 'Belanja Modal Jaringan Telepon Lainnya' },
        { rekening_kode: '5.2.04.04.04', rekening_uraian: 'Belanja Modal Jaringan Gas' },
        { rekening_kode: '5.2.04.04.04.0001', rekening_uraian: 'Belanja Modal Jaringan Pipa Gas Transmisi' },
        { rekening_kode: '5.2.04.04.04.0002', rekening_uraian: 'Belanja Modal Jaringan Pipa Distribusi' },
        { rekening_kode: '5.2.04.04.04.0003', rekening_uraian: 'Belanja Modal Jaringan Pipa Dinas' },
        { rekening_kode: '5.2.04.04.04.0004', rekening_uraian: 'Belanja Modal Jaringan BBM' },
        { rekening_kode: '5.2.04.04.04.0005', rekening_uraian: 'Belanja Modal Jaringan Gas Lainnya' },
        { rekening_kode: '5.1.02.01.01.0039', rekening_uraian: 'Belanja Barang untuk Dijual/Diserahkan kepada Masyarakat' }
    ];

    public async up(queryRunner: QueryRunner): Promise<void> {
        for (const rekening of this.rekenings) {
            await queryRunner.query(
                `INSERT INTO "rekenings" ("rekening_kode", "rekening_uraian")
                 VALUES ($1, $2)
                 ON CONFLICT ("rekening_kode") DO NOTHING`,
                [rekening.rekening_kode, rekening.rekening_uraian],
            );
        }
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const kodeList = this.rekenings.map((r) => r.rekening_kode);
        if (!kodeList.length) return;

        const placeholders = kodeList.map((_, index) => `$${index + 1}`).join(', ');
        await queryRunner.query(
            `DELETE FROM "rekenings" WHERE "rekening_kode" IN (${placeholders})`,
            kodeList,
        );
    }
}
