export const USULAN_JALAN_STATUS = {
    DRAFT: 1,
    DIAJUKAN: 2,
    DISETUJUI: 3,
    DITOLAK: 4,
    VERIFIKASI_INDEX_ADBANG: 5,
    VERIFIKASI_INFORMASI_ADBANG: 6,
    VERIFIKASI_BPKAD: 7,
    VERIFIKASI_BAPPEDA: 8,
} as const;
